### ISSUE TITLE
"Technically Unimpeachable" Paragraph

### ISSUE THREAD

**Issue by sommersoft** [adafruit/Adafruit_Community_Code_of_Conduct#1]
>Don’t just aim to be technically unimpeachable, try to be your best self. In particular, avoid flirting with offensive or sensitive issues, particularly if they’re off-topic; this all too often leads to unnecessary fights, hurt feelings, and damaged trust; worse, it can drive people away from the community entirely.

I'll get the pedantic (non-judgemental!) comment out of the way. I love, love using semi-colons, but there are a couple too many in this sentence.

I have a couple wording suggestions as well, but it's easier just to provide a full sample. 😄 

> The goal of the standards and moderation guidelines outlined above is to build and maintain a respectful community. We ask that you don’t just aim to be "technically unimpeachable", but rather try to be your best self. In particular, avoid offensive or sensitive issues, particularly if they’re off-topic to the channel or discussion. This all too often leads to unnecessary fights, perceptions or instances of disrespect, and damaged community trust. Worse, it can drive people away from the community entirely.

**Comment by tannewt** [comment]
Maybe it would help to explain we value more than technical expertise such as collaboration and support of others.

**Comment by kattni** [comment]
Thank you for taking the time to look through this! I appreciate the the reworded sample. I've utilised it in the CoC. 

I agree with adding wording about what we value as a community - currently figuring out where this wording best fits.

Thanks!

**Comment by kattni** [comment]
Added both suggestions. Closing issue. PR incoming.
